blank_issues_enabled: false
contact_links:
  - name: Web3dev Support
    url: https://discord.com/invite/UXDUzG2hhE
    about: Feel free to ask and answer questions on our discord channel in this server.